import React from 'react'

import {
  BabelLoading,
  BlockLoading,
  BlockReserveLoading,
  BoxLoading,
  CircleLoading,
  CircleToBlockLoading,
  CommonLoading,
  DisappearedLoading,
  LoopCircleLoading,
  NineCellLoading,
  TouchBallLoading,
  TransverseLoading,
  WaveLoading,
  WaveTopBottomLoading,
  WindMillLoading,
  JumpCircleLoading,
  MeteorRainLoading,
  RotateCircleLoading,
  StickyBallLoading,
  SemipolarLoading,
  SolarSystemLoading,
  LadderLoading,
  HeartBoomLoading,
  RollBoxLoading,
  RectGraduallyShowLoading,
  PointSpreadLoading,
  ThreeHorseLoading,
  PassThrouthLoading,
  CoffeeLoading,
  BatteryLoading,
} from "react-loadingg"

const Loaders = ({ divStyle = {}, speed = 1, size = "large" }) => {
  return [
    <BabelLoading divStyle={divStyle} speed={speed} size={size} />,
    <BlockLoading divStyle={divStyle} speed={speed} size={size} />,
    <BlockReserveLoading divStyle={divStyle} speed={speed} size={size} />,
    <BoxLoading divStyle={divStyle} speed={speed} size={size} />,
    <CircleLoading divStyle={divStyle} speed={speed} size={size} />,
    <CircleToBlockLoading divStyle={divStyle} speed={speed} size={size} />,
    <CommonLoading divStyle={divStyle} speed={speed} size={size} />,
    <DisappearedLoading divStyle={divStyle} speed={speed} size={size} />,
    <LoopCircleLoading divStyle={divStyle} speed={speed} size={size} />,
    <NineCellLoading divStyle={divStyle} speed={speed} size={size} />,
    <TouchBallLoading divStyle={divStyle} speed={speed} size={size} />,
    <TransverseLoading divStyle={divStyle} speed={speed} size={size} />,
    <WaveLoading divStyle={divStyle} speed={speed} size={size} />,
    <WaveTopBottomLoading divStyle={divStyle} speed={speed} size={size} />,
    <WindMillLoading divStyle={divStyle} speed={speed} size={size} />,
    <JumpCircleLoading divStyle={divStyle} speed={speed} size={size} />,
    <MeteorRainLoading divStyle={divStyle} speed={speed} size={size} />,
    <RotateCircleLoading divStyle={divStyle} speed={speed} size={size} />,
    <StickyBallLoading divStyle={divStyle} speed={speed} size={size} />,
    <SemipolarLoading divStyle={divStyle} speed={speed} size={size} />,
    <SolarSystemLoading divStyle={divStyle} speed={speed} size={size} />,
    <LadderLoading divStyle={divStyle} speed={speed} size={size} />,
    <HeartBoomLoading divStyle={divStyle} speed={speed} size={size} />,
    <RollBoxLoading divStyle={divStyle} speed={speed} size={size} />,
    <RectGraduallyShowLoading divStyle={divStyle} speed={speed} size={size} />,
    <PointSpreadLoading divStyle={divStyle} speed={speed} size={size} />,
    <ThreeHorseLoading divStyle={divStyle} speed={speed} size={size} />,
    <PassThrouthLoading divStyle={divStyle} speed={speed} size={size} />,
    <CoffeeLoading divStyle={divStyle} speed={speed} size={size} />,
    <BatteryLoading divStyle={divStyle} speed={speed} size={size} />,
  ]
}

export default Loaders